version: '3.8'
services:
    zookeeper:
        image: bitnami/zookeeper:3.9
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ALLOW_ANONYMOUS_LOGIN: "yes"
        networks:
            - app-network
    
    kafka:
        image: bitnami/kafka:3.6
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"       # For internal container communication
            - "9093:9093"       # For host access
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            
            # Listener and Advertised Listener Configuration
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            
            # Allow plaintext listener (disable security for dev)
            ALLOW_PLAINTEXT_LISTENER: "yes"
        networks:
            - app-network
    
    postgres:
        image: postgres:15
        container_name: postgresql
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: finaldb
        ports:
            - "5432:5432"
        networks:
            - app-network
    
    redis:
        image: redis:7
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        networks:
            - app-network
            
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - xpack.security.transport.ssl.enabled=false
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - app-network
        
    kibana:
        image: docker.elastic.co/kibana/kibana:8.13.4
        container_name: kibana
        ports:
            - "5601:5601"
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - SERVER_NAME=kibana
        depends_on:
            - elasticsearch
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
