server:
    port: 8080

spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finaldb}
        username: ${SPRING_DATASOURCE_USERNAME:admin}
        password: ${SPRING_DATASOURCE_PASSWORD:admin}
        driver-class-name: org.postgresql.Driver
    
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    
    data:
        redis:
            host: ${SPRING_REDIS_HOST:localhost}
            port: ${SPRING_REDIS_PORT:6379}
    
    kafka:
        bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    
    elasticsearch:
        uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}

kafka:
    topic:
        name: message-topic
        dlt-name: message-topic.DLT

---
spring:
    config:
        activate:
            on-profile: docker
    
    datasource:
        url: jdbc:postgresql://postgresql:5432/finaldb
        username: admin
        password: admin
    
    data:
        redis:
            host: redis
            port: 6379
    
    kafka:
        bootstrap-servers: kafka:9092
    
    elasticsearch:
        uris: http://elasticsearch:9200
